client.o: proxy.o
	gcc -Wall client.c -o client
proxy.o: 
	gcc -Wall proxy.c -o proxy
clean:
	rm -rf client
	rm -rf proxyserver/proxy
	rm -rf a.out
	rm -rf *.txt
	rm -rf *.jpg
	rm -rf proxyserver/*.txt
	rm -rf proxyserver/*.jpg
